- name: "nvim"
  repo: "neovim/neovim"
  pattern: "nvim-linux-x86_64.appimage"
- name: "mise"
  repo: "jdx/mise"
  pattern: "mise-*-linux-x64"
- name: "atuin"
  repo: "atuinsh/atuin"
  pattern: "atuin-x86_64-unknown-linux-musl.tar.gz"
- name: "ast-grep"
  repo: "ast-grep/ast-grep"
  pattern: "app-x86_64-unknown-linux-gnu.zip"
- name: "bat"
  repo: "sharkdp/bat"
  pattern: "bat-*-x86_64-unknown-linux-musl.tar.gz"
- name: "croc"
  repo: "schollz/croc"
  pattern: "croc_*_Linux-64bit.tar.gz"
- name: "csvlens"
  repo: "YS-L/csvlens"
  pattern: "csvlens-x86_64-unknown-linux-gnu.tar.xz"
- name: "delta"
  repo: "dandavison/delta"
  pattern: "delta-*-x86_64-unknown-linux-musl.tar.gz"
- name: "dua"
  repo: "Byron/dua-cli"
  pattern: "dua-*-x86_64-unknown-linux-musl.tar.gz"
- name: "dust"
  repo: "bootandy/dust"
  pattern: "dust-*-x86_64-unknown-linux-musl.tar.gz"
- name: "eza"
  repo: "eza-community/eza"
  pattern: "eza_x86_64-unknown-linux-musl.tar.gz"
- name: "fd"
  repo: "sharkdp/fd"
  pattern: "fd-*-x86_64-unknown-linux-musl.tar.gz"
- name: "hexyl"
  repo: "sharkdp/hexyl"
  pattern: "hexyl-*-x86_64-unknown-linux-musl.tar.gz"
- name: "hyperfine"
  repo: "sharkdp/hyperfine"
  pattern: "hyperfine-*-x86_64-unknown-linux-musl.tar.gz"
- name: "jq"
  repo: "jqlang/jq"
  pattern: "jq-linux64"
- name: "lazygit"
  repo: "jesseduffield/lazygit"
  pattern: "lazygit_*_linux_x86_64.tar.gz"
- name: "lsd"
  repo: "lsd-rs/lsd"
  pattern: "lsd-*-x86_64-unknown-linux-musl.tar.gz"
- name: "miniserve"
  repo: "svenstaro/miniserve"
  pattern: "miniserve-*-x86_64-unknown-linux-musl"
- name: "ouch"
  repo: "ouch-org/ouch"
  pattern: "ouch-x86_64-unknown-linux-musl.tar.gz"
- name: "procs"
  repo: "dalance/procs"
  pattern: "procs-*-x86_64-linux.zip"
- name: "rg"
  repo: "BurntSushi/ripgrep"
  pattern: "ripgrep-*-x86_64-unknown-linux-musl.tar.gz"
- name: "sad"
  repo: "ms-jpq/sad"
  pattern: "x86_64-unknown-linux-musl.zip"
- name: "sd"
  repo: "chmln/sd"
  pattern: "sd-*-x86_64-unknown-linux-musl.tar.gz"
- name: "tldr"
  repo: "dbrgn/tealdeer"
  pattern: "tealdeer-linux-x86_64-musl"
- name: "watchexec"
  repo: "watchexec/watchexec"
  pattern: "watchexec-*-x86_64-unknown-linux-musl.tar.xz"
- name: "yazi"
  repo: "sxyazi/yazi"
  pattern: "yazi-x86_64-unknown-linux-musl.zip"
